_$.html.asideHTML = [
	'',
	'<h2 class="blind">부메뉴</h2>',
	'',
	'<!-- side -->',
	'<div class="side init">',
	'<menu>',
	'<li><a href="../../html/main/index.html">Main &amp; Notice <span class="required">*readme</span>!</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2" style="background:#480;">Hot Menu</h2>',
	'<menu>',
	'<li class="cs3"><a href="../../html/Reference/article.html">Article</a></li>',
	'<li class="cs3"><a href="../../html/Reference/techtip.html">Tech Tip</a></li>',
	'<li class="cs3"><a href="../../html/Accessibility/accessibility_test.html">WAQM TEST</a></li>',
	'<li class="cs3"><a href="../../html/Guide/UIdev.html">UIdev</a></li>',
	'<li class="cs4"><a href="../../html/dev/LifeCoding.html"><b>LifeCoding</b></a></li>',
	'<li class="cs4 todo"><a href="../../html/Design/Resource.html">Resource <em>*</em></a></li>',
	'<li class="cs4 todo"><a href="../../html/Design/Resource.html">Resource <em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Demo | Lab 〉Lib 〉Tenplate 〉</h2>',
	'<menu>',
	'<li class="cs4"><a href="../../html/Demo/mLab.html">mLab</a></li>',
	'<li class="cs4"><a href="../../html/Demo/mLib.html">mLib</a></li>',
	'<li class="cs4"><a href="../../html/Demo/mTemplate.html">mTemplate</a></li>',
	'<li class="cs4"><a href="../../html/Demo/mProject.html">mProject</a></li>',
	'<li class="cs4"><a href="../../html/Tip/Lab.html">Lab <small class="">old</small></a></li>',
	'<li class="cs4"><a href="../../html/Tip/Lib.html">Lib <small class="">old</small></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2" title="Open Source + API + Mashup + Widgets + Tool">The Modern Web</h2>',
	'<menu>',
	'<li class="cs4"><a href="../../html/Modern/OpenAPI.html">Open API</a></li>',
	'<li class="cs4"><a href="../../html/Modern/map.html">Map</a></li>',
	'<li class="cs4"><a href="../../html/Modern/SNS.html">SNS+Blog</a></li>',
	'<li class="cs4"><a href="../../html/Modern/Tistory.html">Tistory<em>*</em></a></li>',
	'<li class="cs4"><a href="../../html/Modern/WordPress.html">WordPress</a></li>',
	'<li class="cs4"><a href="../../html/Modern/XE.html">XE<em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Modern/RWD.html">RWD (반응형 웹 디자인)</a></li>',
	'<li class="cs6"><a href="../../html/Modern/RWD.FW.html"><b class="em">RWD FrameWork</b></a></li>',
	'<li class="cs4 todo"><a href="../../html/Modern/GitHub.html">GitHub<em>*</em></a></li>',
	'<li class="cs4 todo"><a href="../../html/Modern/Wiki.html">Wiki<em>*</em></a></li>',
	'<li class="cs4 todo"><a href="../../html/Modern/Editor.html">Editor<em>*</em></a></li>',
	'<li class="cs4 todo"><a href="../../html/Modern/VersionControl.html">Version Control<em>*</em></a></li>',
	'<li class="cs4 todo"><a href="../../html/Modern/CodeQuality.html">Code Quality<em>*</em></a></li>',
	'<li class="cs4 todo"><a href="../../html/Modern/Refactoring.html">Refactoring<em>*</em></a></li>',
	'<li class="cs4 todo"><a href="../../html/Modern/Debugging.html">Debugging<em>*</em></a></li>',
	'<li class="cs4 todo"><a href="../../html/Modern/Front-end.html">Front-end<em>*</em></a></li>',
	'<li class="cs4 todo"><a href="../../html/Modern/Build+Task.html">Build+Task<em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Mobile</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Mobile/intro.html">모바일 웹</a></li>',
	'<li class="cs6"><a href="../../html/Mobile/mobile_misc.html">Mobile misc.</a></li>',
	//'<li class="cs6"><a href="../../html/Mobile/mobileOK.html">모바일OK</a></li>',
	'<li class="cs6"><a href="../../html/Mobile/jQueryMobile.html">jQuery Mobile</a></li>',
	'<li class="cs6 todo"><a href="../../html/Mobile/SenchaTouch.html">Sencha Touch <em>*</em></a></li>',
	'<li class="cs6 todo"><a href="../../html/Mobile/PhoneGap.html">PhoneGap <em>*</em></a></li>',
	'<li class="cs6 todo"><a href="../../html/Mobile/Appspresso.html">Appspresso <em>*</em></a></li>',
	'<li><a href="../../html/Note/HTML5API+CSS3+MobileApp.html">[book]HTML5API+CSS3+MobileApp</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">JavaScript</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/JavaScript/javascript_common.html">JS 공통 규정</a></li>',
	'<li class="cs6"><a href="../../html/JavaScript/js_misc.html">JS misc.</a></li>',
	'<li class="cs6"><a href="../../html/JavaScript/compatibility.html">Compatibility</a></li>',
	'<li class="cs6"><a href="../../html/JavaScript/js_tutorial.html">JS Tutorial</a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/Objects.html">Objects</a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/DOM.html">DOM</a></li>',
	'<li class="cs3 todo"><a href="../../html/JavaScript/Function.html">Function <em>*</em></a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/Event.html">Event</a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/Dimensions.html">Dimensions</a></li>',
	'<li class="cs3 todo"><a href="../../html/JavaScript/Effect.html">Effect <em>*</em></a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/Form.html">Form</a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/RegExp.html">RegExp</a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/Algorithm.html">Algorithm<em>*</em></a></li>',
	'<li class="cs9"><a href="../../html/JavaScript/cookie+storage.html">Cookie, Storage, SQL DB</a></li>',
	'<li class="cs12"><a href="../../html/JavaScript/Ajax.html">Ajax | XML, JSON, HTML</a></li>',
	'<li class="cs6"><a href="../../html/JavaScript/Library.html">JavaScript Library</a></li>',
	'<li class="cs6"><a href="../../html/JavaScript/jQuery_tutorial.html">jQuery Tutorial</a></li>',
	'<li class="cs6"><a href="../../html/JavaScript/jquery.html">jQuery</a></li>',
	'<li class="cs6"><a href="../../html/JavaScript/jquery_plugin.html">(jQuery) Plugin</a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/Debug.html">Debug<em>*</em></a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/Test.html">Test<em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Back-end (Server-side)</h2>',
	'<menu>',
	'<li class="cs4"><a href="../../html/Dev/Script.html">Script misc.</a></li>',
	'<li class="cs4"><a href="../../html/Dev/LifeCoding.html"><b>LifeCoding</b></a></li>',
	'<li class="cs4"><a href="../../html/Dev/WebService.html">WebService</a></li>',
	'<li class="cs4"><a href="../../html/Dev/Linux.html">Linux</a></li>',
	'<li class="cs4"><a href="../../html/Dev/DB.html">DB(SQL)</a></li>',
	'<li class="cs4"><a href="../../html/Dev/Node.js.html"><em>*</em> Node.js</a></li>',
	'<li class="cs4"><a href="../../html/Dev/JSP.html">JSP</a></li>',
	'<li class="cs4"><a href="../../html/Dev/PHP.html">PHP</a></li>',
	'<li class="cs4"><a href="../../html/Dev/ASP.html">ASP</a></li>',
	'<li class="cs4 todo"><a href="../../html/Dev/System.html"><em>*</em> System</a></li>',
	'<li class="cs4 todo"><a href="../../html/Dev/OS.html"><em>*</em> OS</a></li>',
	'<li class="cs4"><a href="../../html/Dev/Network.html">Network</a></li>',
	'<li class="cs4 todo"><a href="../../html/Dev/Security.html"><em>*</em> Security</a></li>',
	'<li class="cs6 clb"><a href="../../html/Dev/tool.html">Tool <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Dev/reference.html">Reference <em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Project / Plan / Biz / Culture</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Project/project_misc.html">Project misc.</a></li>',
	'<li class="cs6"><a href="../../html/Project/plan_misc.html">Plan misc.</a></li>',
	'<li class="cs6"><a href="../../html/Project/human.html">Human Resource</a></li>',
	'<li class="cs6 todo"><a href="../../html/Project/process.html"><em>*</em>Process CheckList</a></li>',
	//'<li class="cs6 todo"><a href="../../html/Project/License.html"><em>*</em>License</a></li>',
	'<li class="cs6"><a href="../../html/Project/tool.html">Tool <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Project/reference.html">Reference <em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Design</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Design/design_misc.html">Design misc.</a></li>',
	'<li class="cs6"><a href="../../html/Design/resource.html">Resource <em>*</em></a></li>',
	'<li class="cs6 todo"><a href="../../html/Design/good_design.html">Good Design <em>*</em></a></li>',
	'<li class="cs6 todo"><a href="../../html/Design/Info_graphics.html">Info.Graphics <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Design/tool.html">Tool <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Design/reference.html">Reference <em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">CSS</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/CSS/css_rule_common.html">CSS 공통 규정 <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/CSS/css_misc.html">CSS misc.</a></li>',
	'<li class="cs6"><a href="../../html/CSS/hack.html">Hack</a></li>',
	'<li class="cs6"><a href="../../html/CSS/compatibility.html">Compatibility</a></li>',
	'<li class="cs6"><a href="../../html/CSS/css2.1.html">CSS 2.1</a></li>',
	'<li class="cs6"><a href="../../html/CSS/css3.html">CSS 3</a></li>',
	'<li class="cs6"><a href="../../html/CSS/base.html">Base Reset CSS</a></li>',
	'<li class="cs6"><a href="../../html/Tip/bugfix.html">Bug Fix (CSS)</a></li>',
	'<li class="cs6"><a href="../../html/CSS/@media.html">@media <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/CSS/@font-face.html">@font-face <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/CSS/LESS.html">LESS <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/CSS/SASS.html">SASS <em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Markup</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Markup/(x)html_common.html">(X)HTML 공통 규정</a></li>',
	'<li class="cs6"><a href="../../html/Markup/markup_misc.html">Markup misc.</a></li>',
	'<li class="cs6"><a href="../../html/Markup/markup_sample.html">HTML 4.01</a></li>',
	'<li class="cs6"><a href="../../html/Note/HTML5.html">HTML 5</a></li>',
	'<li class="cs6"><a href="../../html/Markup/HTML5.tp.html">HTML5 Template</a></li>',
	'<li class="cs6"><a href="../../html/Markup/compatibility.html">Compatibility <em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Accessibility | Standard | Compatibility</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Reference/wa.misc.html">웹 접근성 misc.</a></li>',
	'<li class="cs6"><a href="../../html/Accessibility/accessibility_test.html">WA TEST Guide</a></li>',
	'<li class="cs6"><a href="../../html/Accessibility/k-wah.html">K-WAH Tool</a></li>',
	'<li class="cs6"><a href="../../html/Accessibility/screen_reader.html">Screen Reader</a></li>',
	'<li class="cs6"><a href="../../html/Standard/standard.html">웹 표준</a></li>',
	'<li class="cs6"><a href="../../html/Standard/compatibility.html">웹 호환성</a></li>',
	'<li class="cs6"><a href="../../html/Tip/ie_test.html">IE Test</a></li>',
	'<li class="cs6"><a href="../../html/Standard/tool.html">진단도구 Tool</a></li>',
	'<li class="cs6"><a href="../../html/Reference/dtd.html">DTD <em>*</em></a></li>',
	'<li class="cs6"><a>&nbsp;</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Tip&amp;Tech Misc.</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Tip/tip_misc.html">Tip misc.</a></li>',
	'<li class="cs6"><a href="../../html/Tip/RegExp_sample.html">EditPlus RegExp</a></li>',
	'<li class="cs6"><a href="../../html/Tip/character.html">Special Character</a></li>',
	'<li class="cs6"><a href="../../html/Tip/cmd.html">cmd (명령 프롬프트)</a></li>',
	'<li class="cs5"><a href="../../html/Tip/performance.html">Performance<em>*</em></a></li>',
	'<li class="cs3"><a href="../../html/Tip/SEO.html">SEO<em>*</em></a></li>',
	'<li class="cs2"><a href="../../html/Tip/HW.html">HW<em>*</em></a></li>',
	'<li class="cs2"><a href="../../html/Tip/SW.html">SW<em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Reference Link</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Reference/reference.html">[File][Book]</a></li>',
	'<li class="cs6"><a href="../../html/Reference/book_memo.html">[Book]Memo</a></li>',
	'<li class="cs6"><a href="../../html/Reference/site.html">[Site]</a></li>',
	'<li class="cs6"><a href="../../html/Reference/glossary.html">Glossary</a></li>',
	'<li class="cs6"><a href="../../html/Reference/article.html">Article</a></li>',
	'<li class="cs6"><a href="../../html/Reference/techtip.html">Tech Tip</a></li>',
	//'<li class="cs6"><a href="../../html/Reference/ideahint.html">idea Hint</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Guide by m</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Guide/index.html">* Guide Index</a></li>',
	'<li class="cs6"><a href="../../html/Guide/template.html">Template</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Report</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Report/index.html">* Report Index</a></li>',
	'<li class="cs6"><a href="../../html/Report/benchmark.html">Benchmark <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Report/portfolio.html">Portfolio DW+MW</a></li>',
	'<li class="cs6"><a href="../../html/Report/m.portfolio.html">Portfolio MWPic</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">misc.</h2>',
	'<menu>',
	'<li><a href="../../html/misc/test.html">Test</a></li>',
	'</menu>',
	'<p style="margin:.5em 0;"><small class="">Last.Update.20150410. 20150515.</small></p>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'</div>',
	'<!-- /side -->',
	''
];

var asideHTML='';
for(var i in _$.html.asideHTML){
	asideHTML += _$.html.asideHTML[i] + '\n';
}