_$.html.body_footHTML = [
	'',
	'<!-- bfn1 -->',
	'<div id="bfn1">',
	'<ul>',
	'<li class="print"><a href="/share/ui/printpage.html" onclick="window.print();return false;" title="본문 인쇄"><i class="ic1"></i><span class="t1">인쇄</span></a></li>',
	'<li class="gotop"><a href="#container" title="현재 페이지 상단으로 이동"><span class="t1">위로</span></a></li>',
	'</ul>',
	'</div>',
	'<!-- /bfn1 -->',
	'',
	'<!-- charge1 -->',
	'<div id="charge1">',
	'<dl class="contact1">',
	'<dt>담당자</dt>',
	'<dd>사회복지과/장애인복지담당 <a href="tel:000-000-0000" class="phone1" title="전화☎">000-000-0000</span></dd>',
	'</dl>',
	'<dl class="update1">',
	'<dt>최종수정일</dt>',
	'<dd>2015.08.28</dd>',
	'</dl>',
	'</div>',
	'<!-- /charge1 -->',
	'',
	'<!-- satisfy1 -->',
	'<div id="satisfy1">',
	'<form name="formSatisfy1" id="formSatisfy1" method="post" action="?" onsubmit="return doSubmit_satisfyForm(this);">',
	'<fieldset><legend class="blind"><strong class="h1">만족도 조사</strong></legend>',
	'<p class="question" title="질문">현재 열람하신 페이지의 내용이나 사용편의성에 만족하십니까?</p>',
	'<dl class="answer">',
	'<dt class="grade blind">평가:</dt>',
	'<dd class="grade">',
	'<span class="nowrap"><input type="radio" name="satisfy1point" id="satisfy1point5" value="5"><label for="satisfy1point5"><span class="blind">(매우 만족) </span>5점</label></span>',
	'<span class="nowrap"><input type="radio" name="satisfy1point" id="satisfy1point4" value="4"><label for="satisfy1point4"><span class="blind">(만족) </span>4점</label></span>',
	'<span class="nowrap"><input type="radio" name="satisfy1point" id="satisfy1point3" value="3"><label for="satisfy1point3"><span class="blind">(보통) </span>3점</label></span>',
	'<span class="nowrap"><input type="radio" name="satisfy1point" id="satisfy1point2" value="2"><label for="satisfy1point2"><span class="blind">(불만족) </span>2점</label></span>',
	'<span class="nowrap"><input type="radio" name="satisfy1point" id="satisfy1point1" value="1"><label for="satisfy1point1"><span class="blind">(매우 불만족) </span>1점</label></span>',
	'</dd>',
	'<dt class="opinion blind"><label for="satisfy1opinion1">의견:</label></dt>',
	'<dd class="opinion">',
	'<input type="text" name="satisfy1opinion1" id="satisfy1opinion1" value="   여러분의 소중한 한마디를 부탁드립니다." onfocus="this.value=(this.value==\'   여러분의 소중한 한마디를 부탁드립니다.\')?\'\':this.value; this.select();" onblur="this.value=(this.value==\'\')?\'   여러분의 소중한 한마디를 부탁드립니다.\':this.value;" title="여러분의 소중한 한마디를 부탁드립니다." />',
	'</dd>',
	'<dd class="btns">',
	'<button type="submit" value="submit" class="bt1 submit" title="등록하기"><i class="ic1"></i><span class="t1">등록하기</span></button>',
	'<a href="?" onclick="window.open(this.href,\'\',\'width=640,height=640,scrollbars=no,left=20,top=20\');return false;" target="_blank" title="통계보기 (새 창)" class="bt1 stats"><i class="ic1"></i><span class="t1">통계보기</span></a>',
	'</dd>',
	'</dl>',
	'</fieldset>',
	'</form>',
	'</div>',
	'<!-- /satisfy1 -->',
	''
];

var body_footHTML='';
for(var i in _$.html.body_footHTML){
	body_footHTML += _$.html.body_footHTML[i] + '\n';
}