_$.html.footHTML = [
	'',
	'<div class="bg bg2foot"><div></div></div>',
	'<h2 class="blind">하단 정보</h2>',
	'',
	'<!-- #foot_s1 -->',
	'<div id="foot_s1" class="clearfix">',
	'<!-- container -->',
	'<div class="container">',
	'',
	'<!-- familysite1 -->',
	'<div id="familysite1" class="clearfix">',
	'',
	'<!-- familysite1g1 -->',
	'<div id="familysite1g1" class="familysite1g1" data-expand="x2">',
	'<strong class="h1"><a href="#familysite1g1c" class="toggle" title="Work Library 여닫기"><span class="t1">Work Library</span><i class="ic1"></i></a></strong>',
	'<!-- familysite1g1c -->',
	'<div id="familysite1g1c" class="familysite1g1c">',
	'<!-- familysite1g1box -->',
	'<div class="familysite1g1box">',
	'<ul>',
	'<li><a href="http://jspcoding.iacts.co.kr/@m/_lib/" target="_blank" title="새 창">/@m/_lib/</a></li>',
	'</ul>',
	'<strong class="h2">Desktop Template</strong>',
	'<ul>',
	'<li><a href="http://se.yeongdo.go.kr/" target="_blank" title="새 창">Yeongdo Social Enterprise</a></li>',
	'</ul>',
	'<strong class="h2">Mobile Template</strong>',
	'<ul>',
	'<li><a href="http://mayor.gimhae.go.kr/" target="_blank" title="새 창">Gimhae Mayor</a></li>',
	'</ul>',
	'<strong class="h2">RWD(AWD) Template</strong>',
	'<ul>',
	'<li><a href="http://www.namhae.go.kr/" target="_blank" title="새 창">Namhae</a></li>',
	'<li><a href="http://www.geochang.go.kr/" target="_blank" title="새 창">Geochang</a></li>',
	'</ul>',
	'</div>',
	'<!-- /familysite1g1box -->',
	'<a href="#familysite1g1c" class="b1 close">Work Library 닫기</a>',
	'</div>',
	'<!-- /familysite1g1c -->',
	'</div>',
	'<!-- /familysite1g1 -->',
	'',
	'<!-- familysite1g2 -->',
	'<div id="familysite1g2" class="familysite1g1">',
	'<strong class="h1"><a href="#familysite1g2c" class="toggle" title="Project Progress 여닫기"><span class="t1">Project Progress</span><i class="ic1"></i></a></strong>',
	'<!-- familysite1g2c -->',
	'<div id="familysite1g2c" class="familysite1g1c">',
	'<!-- familysite1g1box -->',
	'<div class="familysite1g1box">',
	'<strong class="h2">그룹2분류1</strong>',
	'<ul>',
	'<li><a href="../../html/main/index.html">Web</a></li>',
	'<li><a href="../../[Lang]/index.html">Lang</a></li>',
	'<li><a href="../../[Life]/index.html">Life</a></li>',
	'<li><a href="../../html/Note/+-note.html" onclick="window.open(this.href,\'_top\'); return false;">Note</a></li>',
	'</ul>',
	'<strong class="h2">그룹2분류2</strong>',
	'<ul>',
	'<li><a href="../../html/main/index.html">Web</a></li>',
	'<li><a href="../../[Lang]/index.html">Lang</a></li>',
	'<li><a href="../../[Life]/index.html">Life</a></li>',
	'<li><a href="../../Note/+-note.html" onclick="window.open(this.href,\'_top\'); return false;">Note</a></li>',
	'</ul>',
	'</div>',
	'<!-- /familysite1g1box -->',
	'<a href="#familysite1g2c" class="b1 close">Project Progress 닫기</a>',
	'</div>',
	'<!-- /familysite1g2c -->',
	'</div>',
	'<!-- /familysite1g2 -->',
	'',
	'<!-- familysite1g3 -->',
	'<div id="familysite1g3" class="familysite1g1">',
	'<strong class="h1"><a href="#familysite1g3c" class="toggle" title="패밀리사이트1그룹3 여닫기"><span class="t1">패밀리사이트1그룹3</span><i class="ic1"></i></a></strong>',
	'<!-- familysite1g3c -->',
	'<div id="familysite1g3c" class="familysite1g1c">',
	'<!-- familysite1g1box -->',
	'<div class="familysite1g1box">',
	'<ul>',
	'<li><a href="../../html/main/index.html">Web</a></li>',
	'<li><a href="../../[Lang]/index.html">Lang</a></li>',
	'<li><a href="../../[Life]/index.html">Life</a></li>',
	'<li><a href="../../html/Note/+-note.html" onclick="window.open(this.href,\'_top\'); return false;">Note</a></li>',
	'</ul>',
	'<ul>',
	'<li><a href="../../html/main/index.html">Web</a></li>',
	'<li><a href="../../[Lang]/index.html">Lang</a></li>',
	'<li><a href="../../[Life]/index.html">Life</a></li>',
	'<li><a href="../../Note/+-note.html" onclick="window.open(this.href,\'_top\'); return false;">Note</a></li>',
	'</ul>',
	'</div>',
	'<!-- /familysite1g1box -->',
	'<a href="#familysite1g3c" class="b1 close">패밀리사이트1그룹3 닫기</a>',
	'</div>',
	'<!-- /familysite1g3c -->',
	'</div>',
	'<!-- /familysite1g3 -->',
	'',
	'</div>',
	'<!-- /familysite1 -->',
	'',
	'</div>',
	'<!-- /container -->',
	'</div>',
	'<!-- /#foot_s1 -->',
	'',
	'<!-- #foot_s2 -->',
	'<div id="foot_s2" class="clearfix">',
	'<!-- container -->',
	'<div class="container">',
	'',
	'<div id="snslink1">',
	'<strong class="h1 blind">소셜/링크</strong>',
	'<ul>',
	'<li class="mail"><a href="?" target="_blank" title="새 창"><i class="ic1"></i><span class="t1">메일</span></a></li>',
	'<li class="facebook"><a href="?" target="_blank" title="새 창"><i class="ic1"></i><span class="t1">페이스북</span></a></li>',
	'<li class="twitter"><a href="http://twitter.com/moonyscene" target="_blank" title="새 창"><i class="ic1"></i><span class="t1">트위터</span></a></li>',
	'<li class="youtube"><a href="?" target="_blank" title="새 창"><i class="ic1"></i><span class="t1">유투브</span></a></li>',
	'</ul>',
	'</div>',
	'',
	'<a href="/" id="foot_logo">mNote</a>',
	'',
	'<div id="fn1">',
	'<strong class="h1 blind">안내/정책</strong>',
	'<ul>',
	'<li class="m1"><a href="?"><b>개인정보처리방침</b></a></li>',
	'<li class="m2"><a href="../../html/main/index.html">Web</a></li>',
	'<li class="m3"><a href="../../[Lang]/index.html">Lang</a></li>',
	'<li class="m4"><a href="../../[Life]/index.html">Life</a></li>',
	'<li class="m5"><a href="../../Note/+-note.html" onclick="window.open(this.href,\'_top\'); return false;">Note</a></li>',
	'</ul>',
	'</div>',
	'',
	'</div>',
	'<!-- /container -->',
	'</div>',
	'<!-- /#foot_s2 -->',
	'',
	'<!-- #foot_s3 -->',
	'<div id="foot_s3" class="clearfix">',
	'<!-- container -->',
	'<div class="container">',
	'',
	'<div id="visitor1">',
	'<strong class="h1 blind">방문자</strong>',
	'<dl>',
	'<dt class="total"><b>전체</b> :</dt>',
	'<dd class="total">1,234,567명</dd>',
	'<dt class="today"><b>오늘</b> :</dt>',
	'<dd class="today">1,234명</dd>',
	'</dl>',
	'</div>',
	'',
	'<div id="author1">',
	'<strong class="h1 blind">작성자 (연락처/저작권)</strong>',
	'<address class="address">000-000 우리시 우리구 우리동 1470 우리빌딩, 808호.　&nbsp;<span class="nowrap">TEL. 000-000-0000 &nbsp;FAX. 000-000-0000</span></address>',
	'<p class="nophishing">본 웹사이트에 게시된 이메일주소가 자동 수집되는 것을 거부하며, <span class="nowrap">이를 위반시 정보통신망법에 의해 처벌됨을 유념하시기 바랍니다.</span></p>',
	'<address class="copyright">Copyright &copy; 2007.03.02 <cite>mNote.v2</cite> written by <a href="mailto:myshin(at)naver.com">MoonYoungshin</a>. <span class="nowrap">All rights reserved.</span></address>',
	'</div>',
	'',
	'</div>',
	'<!-- /container -->',
	'</div>',
	'<!-- /#foot_s3 -->',
	''
];

var footHTML= '';
for(var i in _$.html.footHTML){
	footHTML += _$.html.footHTML[i] + '\n';
}