_$.html.headHTML = [
	'',
	'<div class="bg bg2head"><div></div></div>',
	'',
	'<!-- container -->',
	'<div class="container">',
	'<h1 id="logo"><a href="../../index.html" title="홈으로 이동"><small class="blind">(logo)</small>mNote.v2</a></h1>',
	'</div>',
	'<!-- /container -->',
	'',
	'<h2 class="blind">상단 메뉴</h2>',
	'',
	'<!-- #head_s1 -->',
	'<div id="head_s1" class="clearfix">',
	'<!-- container -->',
	'<div class="container">',
	'',
	'<!-- gn3 -->',
	'<div id="gn3">',
	'<strong class="blind">Global Navigation</strong>',
	'<ul>',
	'<li><a href="?" onclick="history.go(-1); return false;"><i class="material-icons md-24" style="font-size:12px;">arrow_back</i><span class="t1">Back</span></a></li>',
	'</ul>',
	'</div>',
	'<!-- /gn3 -->',
	'',
	'<!-- gn1 -->',
	'<div id="gn1">',
	'<strong class="blind">Global Navigation</strong>',
	'<ul>',
	'<li class="m"><a href="../../">홈</a></li>',
	'<li class="m"><a href="../../html/sub/sitemap.html">사이트맵</a></li>',
	'<li class="m gomenu"><a href="#aside">Aside</a></li>',
	//'<li class="m join"><a href="../../html/member/join.html">Join</a></li>',
	//'<li class="m login"><a href="../../html/member/login.html">Login</a></li>',
	//'<li class="m modify"><a href="../../html/member/modify.html" title="회원정보수정"><b class="user">전우치</b> 님</a></li>',
	//'<li class="m logout"><a href="../../html/member/logout.html">Logout</a></li>',
	'</ul>',
	'</div>',
	'<!-- /gn1 -->',
	'',
	'<!-- gn2 -->',
	'<div id="gn2">',
	'<a href="#gn2c" class="toggle slide"><span class="t1">Language</span><i class="ic1"></i></a>',
	'<!-- gn2c -->',
	'<div id="gn2c">',
	'<strong class="h1 blind">Global Navigation : Language</strong>',
	'<ul>',
	'<li lang="en"><a href="?" target="_blank" title="새 창">English</a></li>',
	'<li lang="zh"><a href="?" target="_blank" title="새 창">中文</a></li>',
	'<li lang="ja"><a href="?" target="_blank" title="새 창">日文</a></li>',
	'</ul>',
	'</div>',
	'<!-- /gn2c -->',
	'</div>',
	'<!-- /gn2 -->',
	'',
	'</div>',
	'<!-- /container -->',
	'</div>',
	'<!-- /#head_s1 -->',
	'',
	'<!-- #head_s2 -->',
	'<div id="head_s2" class="clearfix">',
	'<!-- container -->',
	'<div class="container">',
	'',
	'<!-- tnb1 [jQ] $("#tnb1").on(..) -->',
	'<div id="tnb1"><div class="bg"></div>',
	'<strong class="h1"><a href="#tnb1c" class="b1 toggle donot">주 메뉴 여닫기</a></strong>',
	'<!-- d1 -->',
	'<div class="d1" id="tnb1c"><div class="bg"></div>',
	'<ul>',
	'<li class="m1"><a href="?">Demo</a>',
	'	<div class="d2"><div class="bg"><i class="deco1"></i><i class="deco2"></i></div>',
	'	<ul>',
	'	<li class="m1"><a href="?">메뉴1-1</a>',
	'		<div class="d3">',
	'		<ul>',
	'		<li class="m1"><a href="?">메뉴1-1-1</a>',
	'			<div class="d4">',
	'			<ul>',
	'			<li class="m1"><a href="?">메뉴1-1-1-1</a></li>',
	'			<li class="m2"><a href="?">메뉴1-1-1-2</a></li>',
	'			<li class="m3"><a href="?">메뉴1-1-1-3</a></li>',
	'			</ul>',
	'			</div>',
	'		</li>',
	'		<li class="m2"><a href="?">메뉴1-1-2</a></li>',
	'		<li class="m3"><a href="?">메뉴1-1-3</a></li>',
	'		</ul>',
	'		</div>',
	'	</li>',
	'	<li class="m2"><a href="?">메뉴1-2. 메뉴명이 다중 행이면 어떻게 표현하는가?  메뉴명이 다중 행이면 어떻게 표현하는가?  메뉴명이 다중 행이면 어떻게 표현하는가?</a>',
	'		<div class="d3">',
	'		<ul>',
	'		<li class="m1"><a href="?">메뉴1-2-1</a>',
	'			<div class="d4">',
	'			<ul>',
	'			<li class="m1"><a href="?">메뉴1-2-1-1</a></li>',
	'			<li class="m2"><a href="?">메뉴1-2-1-2</a></li>',
	'			<li class="m3"><a href="?">메뉴1-2-1-3</a></li>',
	'			</ul>',
	'			</div>',
	'		</li>',
	'		<li class="m2"><a href="?">메뉴1-2-2</a></li>',
	'		<li class="m3"><a href="?">메뉴1-2-3</a></li>',
	'		</ul>',
	'		</div>',
	'	</li>',
	'	<li class="m3"><a href="?">메뉴1-3</a>',
	'		<div class="d3">',
	'		<ul>',
	'		<li class="m1"><a href="?">메뉴1-3-1</a>',
	'			<div class="d4">',
	'			<ul>',
	'			<li class="m1"><a href="?">메뉴1-3-1-1</a></li>',
	'			<li class="m2"><a href="?">메뉴1-3-1-2</a></li>',
	'			<li class="m3"><a href="?">메뉴1-3-1-3</a></li>',
	'			<li class="m4"><a href="?">메뉴1-3-1-4</a></li>',
	'			</ul>',
	'			</div>',
	'		</li>',
	'		<li class="m2"><a href="?">메뉴1-3-2</a></li>',
	'		<li class="m3"><a href="?">메뉴1-3-3</a></li>',
	'		</ul>',
	'		</div>',
	'	</li>',
	'	<li class="m4"><a href="?">메뉴1-4</a></li>',
	'	<li class="m5"><a href="?">메뉴1-5</a></li>',
	'	<li class="m6"><a href="?">메뉴1-6</a></li>',
	'	</ul>',
	'	</div>',
	'</li>',
	'<li class="m2"><a href="?">Modern</a>',
	'	<div class="d2"><div class="bg"><i class="deco1"></i><i class="deco2"></i></div>',
	'	<ul>',
	'	<li class="m1"><a href="?">메뉴2-1</a></li>',
	'	<li class="m2"><a href="?">메뉴2-2</a></li>',
	'	<li class="m3"><a href="?">메뉴2-3</a></li>',
	'	</ul>',
	'	</div>',
	'</li>',
	'<li class="m3"><a href="?">Mobile</a>',
	'	<div class="d2"><div class="bg"><i class="deco1"></i><i class="deco2"></i></div>',
	'	<ul>',
	'	<li class="m1"><a href="?">메뉴3-1</a></li>',
	'	<li class="m2"><a href="?">메뉴3-2</a></li>',
	'	<li class="m3"><a href="?">메뉴3-3</a></li>',
	'	</ul>',
	'	</div>',
	'</li>',
	'<li class="m4"><a href="?">JavaScript</a>',
	'	<div class="d2"><div class="bg"><i class="deco1"></i><i class="deco2"></i></div>',
	'	<ul>',
	'	<li class="m1"><a href="?">메뉴4-1</a></li>',
	'	<li class="m2"><a href="?">메뉴4-2</a></li>',
	'	<li class="m3"><a href="?">메뉴4-3</a></li>',
	'	</ul>',
	'	</div>',
	'</li>',
	'<li class="m5"><a href="?">Back-end</a>',
	'	<div class="d2"><div class="bg"><i class="deco1"></i><i class="deco2"></i></div>',
	'	<ul>',
	'	<li class="m1"><a href="?">메뉴5-1</a></li>',
	'	<li class="m2"><a href="?">메뉴5-2</a></li>',
	'	<li class="m3"><a href="?">메뉴5-3</a></li>',
	'	</ul>',
	'	</div>',
	'</li>',
	'<li class="m6"><a href="?">Project</a>',
	'	<div class="d2"><div class="bg"><i class="deco1"></i><i class="deco2"></i></div>',
	'	<ul>',
	'	<li class="m1"><a href="?">메뉴6-1</a></li>',
	'	<li class="m2"><a href="?">메뉴6-2</a></li>',
	'	<li class="m3"><a href="?">메뉴6-3</a></li>',
	'	</ul>',
	'	</div>',
	'</li>',
	'</ul>',
	'</div>',
	'<!-- /d1 -->',
	'</div>',
	'<!-- /tnb1 -->',
	'',
	'<!-- search1 -->',
	'<div id="search1">',
	'<form action="?">',
	'<fieldset><legend class="blind"><strong class="h1">통합검색</strong></legend>',
	'<label for="search1keyword" class="blind">검색어</label>',
	'<input type="text" name="search1keyword" id="search1keyword" value=" 검색어를 입력해주세요." onfocus="this.value=(this.value==\' 검색어를 입력해주세요.\')?\'\':this.value; this.select();" onblur="this.value=(this.value==\'\')?\' 검색어를 입력해주세요.\':this.value; this.style.color=\'#959595\'" title=" 검색어를 입력해주세요." class="text" />',
	'<button type="submit" value="submit" class="button submit"><i class="ic1"></i><span class="t1 blind">검색</span></button>',
	'</fieldset>',
	'</form>',
	'</div>',
	'<!-- /search1 -->',
	'',
	'</div>',
	'<!-- /container -->',
	'</div>',
	'<!-- /#head_s2 -->',
	'',
	'<!-- #head_s3 -->',
	'<div id="head_s3" class="clearfix">',
	'<!-- container -->',
	'<div class="container">',
	'',
	'</div>',
	'<!-- /container -->',
	'</div>',
	'<!-- /#head_s3 -->',
	''
];

var headHTML= '';
for(var i in _$.html.headHTML){
	headHTML += _$.html.headHTML[i] + '\n';
}