_$.html.sideHTML = [
	'',
	'<h2 class="blind">SideMenu</h2>',
	'',
	'<!-- side -->',
	'<div class="side init">',
	'<menu>',
	'<li><a href="../../html/main/index.html">Main &amp; Notice <span class="required">*readme</span>!</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2" style="background:#480;">Hot Menu</h2>',
	'<menu>',
	'<li class="cs3"><a href="../../html/Note/Note.html">Note</a></li>',
	'<li class="cs3"><a href="../../html/Reference/article.html">Article</a></li>',
	'<li class="cs4"><a href="../../html/Reference/techtip.html">Tech Tip</a></li>',
	'<li class="cs2"><a href="../../html/Reference/link.html">Link</a></li>',
	'<li class="cs3"><a href="../../html/Guide/UIdev.html">UIdev</a></li>',
	//'<li class="cs5"><a href="../../html/Accessibility/accessibility_test.html">WAQM TEST</a></li>',
	'<li class="cs4"><a href="../../html/Test/QM_TEST.html">QM TEST</a></li>',
	'<li class="cs4"><a href="../../html/Design/resource.html"><b class="">Resource</b></a></li>',
	'<li class="cs4"><a href="../../html/Report/portfolio.html">Portfolio</a></li>',
	'<li class="cs5"><a href="../../html/CheatSheet/index.html">Cheat Sheet</a></li>',
	'<li class="cs3"><a href="../../html/x.html">x</a></li>',
	'<li class="cs6"><a href="../../html/Note/_tp.subcontent.html">_tp.subcontent</a></li>',
	'<li class="cs6"><a href="../../html/Print/_pt.maker.html">_pt.maker</a></li>',
	'<li><a href="../../__lab.make/01.b.mIAMarkup/mIAMarkup.html"><b class="em0">Make IA Markup.jsp(실험실)</b></a>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Demo | Lab 〉Lib 〉Template 〉</h2>',
	'<menu>',
	'<li class="cs3"><a href="../../html/Demo/mLab.html"><b class="em1">mLab</b></a></li>',
	'<li class="cs4"><a href="../../html/Demo/mLib.html"><b class="em2">mLib</b></a></li>',
	'<li class="cs5"><a href="../../html/Demo/mTemplate.html">mTemplate</a></li>',
	'<li class="cs4"><a href="../../html/Demo/mProject.html">mProject</a></li>',
	'<li class="cs4"><a href="../../html/Tip/Lab.html">Lab <small class="">old</small></a></li>',
	'<li class="cs4"><a href="../../html/Tip/Lib.html">Lib <small class="">old</small></a></li>',
	'<li class="cs4"><a href="../../html/Demo/chart/mChart.html"><b class="em1">mChart</b></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2" title="Open Source + API + Mashup + Widgets + Tool">The Modern Web</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Modern/Front-End.html"><b class="em3">Front-End Dev</b></a></li>',
	'<li class="cs6"><a href="../../html/Modern/OSS.html">OSS</a></li>',
	'<li class="cs6"><a href="../../html/Modern/RWD.html"><b class="em4">RWD</b> (반응형 웹 디자인)</a></li>',
	'<li class="cs6"><a href="../../html/Modern/RWD.FW.html"><b class="em4-5">RWD FrameWork</b></a></li>',
	'<li class="cs6"><a href="../../html/Mobile/mobile_intro.html">모바일 웹</a></li>',
	'<li class="cs6"><a href="../../html/Mobile/mobile_misc.html">Mobile misc.</a></li>',
	'<li class="cs3"><a href="../../html/Modern/Editor.html">Editor</a></li>',
	'<li class="cs3"><a href="../../html/Modern/VCS.html">VCS</a></li>',
	'<li class="cs6 todo"><a href="../../html/Modern/CodeQuality.html">Code Quality</a></li>',
	'<li class="cs4 todo"><a href="../../html/Modern/Refactory.html">Refactory</a></li>',
	'<li class="cs3 todo"><a href="../../html/Modern/Debug.html">Debug</a></li>',
	'<li class="cs5 todo"><a href="../../html/Modern/Build+Task.html">Build+Task</a></li>',
	'<li class="cs4"><a href="../../html/Modern/ReactJS.html">ReactJS</a></li>',
	'<li class="cs4"><a href="../../html/Modern/VueJS.html">VueJS</a></li>',
	'<li class="cs4"><a href="../../html/Modern/AngulaJS.html">AngulaJS</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">JavaScript &amp; jQuery</h2>',
	'<menu>',
	'<li class="cs4"><a href="../../html/JavaScript/javascript_common.html">JS Rule</a></li>',
	'<li class="cs4"><a href="../../html/JavaScript/js_misc.html"><b class="em7">JS misc.</b></a></li>',
	'<li class="cs4"><a href="../../html/JavaScript/js_tutorial.html"><b class="em5-6">JS Tutorial</b></a></li>',
	'<li class="cs6"><a href="../../html/JavaScript/ES5.html"><b class="em5-6">ES5</b> [IE10+] *</a></li>',
	'<li class="cs6"><a href="../../html/JavaScript/ES6.html"><b class="em5-6">ES6</b> [EG14] *</a></li>',
	'<li class="cs4"><a href="../../html/JavaScript/RegExp.html">RegExp</a></li>',
	'<li class="cs4"><a href="../../html/JavaScript/Algorithm.html">Algorithm</a></li>',
	'<li class="cs4"><a href="../../html/JavaScript/Form.html">Form</a></li>',
	'<li class="cs4"><a href="../../html/JavaScript/Debug.html">Debug<em>*</em></a></li>',
	'<li class="cs4"><a href="../../html/JavaScript/Test.html">Test<em>*</em></a></li>',
	'<li class="cs4"><a href="../../html/JavaScript/Library.html">Library</a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/jQuery.html">jQuery</a></li>',
	'<li class="cs5"><a href="../../html/JavaScript/jQuery_tutorial.html"><b class="em5-6">jQ Tutorial</b></a></li>',
	'<li class="cs4"><a href="../../html/JavaScript/jQuery_animation.html">Animation</a></li>',
	//'<li class="cs5"><a href="../../html/JavaScript/jQuery_plugin.html"><b class="em7">Plugin (jQ)</b></a></li>',
	'<li class="cs5"><a href="../../html/JavaScript/Plugin_jQuery.html"><b class="em7">Plugin (jQ)</b></a></li>',
	'<li class="cs3"><a href="../../html/JavaScript/BP.html"><b class="em9">BP</b></a></li>',
	'<li class="cs4"><a href="../../html/JavaScript/BP.OOP.html">BP.OOP</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">CSS</h2>',
	'<menu>',
	'<li class="cs4"><a href="../../html/CSS/css_rule_common.html">CSS Rule</a></li>',
	'<li class="cs4"><a href="../../html/CSS/css_misc.html">CSS misc.</a></li>',
	'<li class="cs4"><a href="../../html/Tip/bugfix.html"><b class="em">BugFix (CSS)</b></a></li>',
	'<li class="cs4"><a href="../../html/CSS/css2.1.html">CSS 2.1</a></li>',
	'<li class="cs3"><a href="../../html/CSS/css3.html"><b class="em6">CSS 3</b></a></li>',
	'<li class="cs5"><a href="../../html/CSS/@font-face.html"><b class="em6">@font-face</b></a></li>',
	'<li class="cs3"><a href="../../html/CSS/grid12.html"><b class="em8">Grid</b></a></li>',
	'<li class="cs3"><a href="../../html/CSS/shape.html"><b class="em7">Shape</b></a></li>',
	'<li class="cs6"><a href="../../html/CSS/animation.html"><b class="em8">Animation</b></a></li>',
	'<li class="cs6"><a href="../../html/CSS/LESS.html">LESS <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/CSS/SASS.html">SASS <em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Markup</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Markup/(x)html_common.html">(X)HTML Rule</a></li>',
	'<li class="cs6"><a href="../../html/Markup/markup_misc.html">Markup misc.</a></li>',
	'<li class="cs6"><a href="../../html/Markup/markup_sample.html">HTML 4.01</a></li>',
	'<li class="cs6"><a href="../../html/Note/HTML5.html"><b class="em8">HTML 5</b></a></li>',
	'<li class="cs6"><a href="../../html/Markup/compatibility.html">Compatibility <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Markup/svg.html"><b class="em1">SVG</b></a></li>',
	'<li class="cs6"><a href="../../html/Markup/canvas.html"><b class="em2">Canvas</b></a></li>',
	'<li class="cs6"><a href="../../html/Markup/WAI-ARIA.html"><b class="em7">WAI-ARIA <em>*</em></b></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Design</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Design/design_misc.html">Design misc.</a></li>',
	'<li class="cs6"><a href="../../html/Design/link.html"><b class="em7">Link : Res, Ref</b></a></li>',
	'<li class="cs3"><a href="../../html/Design/color.html">Color</a></li>',
	'<li class="cs5"><a href="../../html/Design/typography.html"><b class="em8">Typography</b></a></li>',
	'<li class="cs4"><a href="../../html/Design/shape.html">Shape</a></li>',
	'<li class="cs6"><a href="../../html/Design/good_design.html">Good Design</a></li>',
	'<li class="cs6"><a href="../../html/Design/Info_graphics.html">Info Graphics</a></li>',
	'<li class="cs6"><a href="../../html/Design/tool.html">Tool</a></li>',
	'<li class="cs6"><a href="../../html/Design/reference.html">Reference</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Back-end (Server-side)</h2>',
	'<menu>',
	'<li class="cs5"><a href="../../html/Dev/Script.html">Script misc.</a></li>',
	'<li class="cs3"><a href="../../html/Dev/WAS.html">WAS</a></li>',
	'<li class="cs4"><a href="../../html/Dev/LifeCoding.html"><b class="em9">LifeCoding</b></a></li>',
	'<li class="cs4"><a href="../../html/Dev/WebService.html">WebService</a></li>',
	'<li class="cs4"><a href="../../html/Dev/Linux.html">Linux</a></li>',
	'<li class="cs4"><a href="../../html/Dev/DB.html">DB(SQL)</a></li>',
	'<li class="cs4"><a href="../../html/Dev/Node.js.html">Node.js <em>*</em></a></li>',
	'<li class="cs4"><a href="../../html/Dev/JSP.html">JSP</a></li>',
	'<li class="cs4"><a href="../../html/Dev/Python.html">Python</a></li>',
	'<li class="cs4"><a href="../../html/Dev/PHP.html">PHP</a></li>',
	'<li class="cs4"><a href="../../html/Dev/ASP.html">ASP</a></li>',
	'<li class="cs4 todo"><a href="../../html/Dev/System.html"><em>*</em> System</a></li>',
	'<li class="cs4 todo"><a href="../../html/Dev/OS.html"><em>*</em> OS</a></li>',
	'<li class="cs4"><a href="../../html/Dev/Network.html">Network</a></li>',
	'<li class="cs4 todo"><a href="../../html/Dev/Security.html"><em>*</em> Security</a></li>',
	'<li class="cs6 clb"><a href="../../html/Dev/tool.html">Tool <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Dev/reference.html">Reference <em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2"><a href="../../html/Project/index.html">Project / Plan / Biz / Culture</a></h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Project/project_misc.html">Project misc.</a></li>',
	'<li class="cs6"><a href="../../html/Project/plan_misc.html">Plan misc.</a></li>',
	'<li class="cs6"><a href="../../html/Project/human.html">Human Resource</a></li>',
	'<li class="cs6 todo"><a href="../../html/Project/process.html"><em>*</em>Process CheckList</a></li>',
	//'<li class="cs6 todo"><a href="../../html/Project/License.html"><em>*</em>License</a></li>',
	'<li class="cs6"><a href="../../html/Project/tool.html">Tool <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Project/reference.html">Reference <em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Accessibility | Standard | Compatibility</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Reference/wa.misc.html">웹 접근성 misc.</a></li>',
	'<li class="cs6"><a href="../../html/Accessibility/accessibility_test.html">WA TEST Guide</a></li>',
	'<li class="cs6"><a href="../../html/Accessibility/k-wah.html">K-WAH Tool</a></li>',
	'<li class="cs6"><a href="../../html/Accessibility/screen_reader.html">Screen Reader</a></li>',
	'<li class="cs6"><a href="../../html/Standard/standard.html">웹 표준</a></li>',
	'<li class="cs6"><a href="../../html/Standard/compatibility.html">웹 호환성</a></li>',
	'<li class="cs6"><a href="../../html/Tip/ie_test.html">IE Test</a></li>',
	'<li class="cs6"><a href="../../html/Standard/tool.html">진단도구 Tool</a></li>',
	'<li class="cs6"><a href="../../html/Reference/dtd.html">DTD <em>*</em></a></li>',
	'<li class="cs6"><a>&nbsp;</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Tip&amp;Tech Misc.</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Tip/tip_misc.html">Tip misc.</a></li>',
	'<li class="cs6"><a href="../../html/Tip/RegExp_sample.html">EditPlus RegExp</a></li>',
	'<li class="cs6"><a href="../../html/Tip/character.html">Special Character</a></li>',
	'<li class="cs6"><a href="../../html/Tip/cmd.html">cmd (명령 프롬프트)</a></li>',
	'<li class="cs6"><a href="../../html/Tip/performance.html">Performance<em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Tip/SEO.html">SEO<em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Tip/HW.html">HW<em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Tip/SW.html">SW<em>*</em></a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Reference Link</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Reference/reference.html">[File][Book]</a></li>',
	'<li class="cs6"><a href="../../html/Reference/book_memo.html">[Book]Memo</a></li>',
	'<li class="cs6"><a href="../../html/Reference/site.html">[Site]</a></li>',
	'<li class="cs6"><a href="../../html/Reference/glossary.html">Glossary</a></li>',
	'<li class="cs6"><a href="../../html/Reference/article.html">Article</a></li>',
	'<li class="cs6"><a href="../../html/Reference/techtip.html">Tech Tip</a></li>',
	//'<li class="cs6"><a href="../../html/Reference/ideahint.html">idea Hint</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Guide by m</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Guide/index.html">* Guide Index</a></li>',
	'<li class="cs6"><a href="../../html/Guide/template.html">Template</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Report</h2>',
	'<menu>',
	'<li class="cs6"><a href="../../html/Report/index.html">* Report Index</a></li>',
	'<li class="cs6"><a href="../../html/Report/benchmark.html">Benchmark <em>*</em></a></li>',
	'<li class="cs6"><a href="../../html/Report/portfolio.html">Portfolio <!-- DW+MW --></a></li>',
	'<li class="cs6"><a href="../../html/Report/m.portfolio.html">Portfolio MWPic</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">misc.</h2>',
	'<menu>',
	'<li class="cs4"><a href="../../html/misc/test.html">Test</a></li>',
	'<li class="cs4"><a href="../../html/misc/print.html">Print</a></li>',
	'<li class="cs4"><a href="../../html/Note/Note.html">Note</a></li>',
	'</menu>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'<h2 class="h2">Language</h2>',
	'<menu>',
	'<li class="cs2"><a href="../../html/Lang/ko1.html">ko</a></li>',
	'<li class="cs2"><a href="../../html/Lang/en1.html">en</a></li>',
	'<li class="cs3"><a href="../../html/Lang/math1.html">math</a></li>',
	'</menu>',
	'<p style="margin:.5em 0;"><small class="">History.20150410~20170427. 20171016.</small></p>',
	'', /* ◇◆◇◆◇◆◇◆◇◆◇◆ */
	'</div>',
	'<!-- /side -->',
	''
];

var sideHTML='';
for(var i in _$.html.sideHTML){
	sideHTML += _$.html.sideHTML[i] + '\n';
}